server:
  port: 8080
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-server
          uri: http://localhost:9001
          predicates:
            - Path=/api/auth/**
        - id: message-server
          uri: http://localhost:9101
          predicates:
            - Path=/api/message/**
        - id: user-server
          uri: http://localhost:9201
          predicates:
            - Path=/api/user/**
        - id: video-server
          uri: http://localhost:9301
          predicates:
            - Path=/api/video/**
        - id: file-server
          uri: http://localhost:9401
          predicates:
            - Path=/api/file/**